import { createPortal } from "react-dom";
import type { AssessmentResult } from "../lib/types";

const LEVEL_COLOR: Record<string, string> = { LOW: "#15803D", MODERATE: "#B45309", HIGH: "#B91C1C" };

function val(v: unknown, unit = ""): string {
  return v === null || v === undefined || v === "" ? "Not provided" : `${v}${unit}`;
}

/**
 * One-page report used by "Save as PDF". It is only visible when printing
 * (see @media print in index.css), so it never affects the normal page.
 */
export function PrintReport({ a }: { a: AssessmentResult }) {
  const i = a.inputs;
  const nearby = [i.nearby_homes && "homes", i.nearby_playground && "playground or school", i.nearby_farm_animals && "farm animals"]
    .filter(Boolean)
    .join(", ");
  const contributions = a.risk.contributions
    .filter((c) => c.human + c.animal + c.ecosystem > 0.001)
    .sort((x, y) => y.human + y.animal + y.ecosystem - (x.human + x.animal + x.ecosystem));
  const findings = [...a.findings].sort((x, y) => y.confidence - x.confidence);
  const date = new Date(a.created_at).toLocaleString();

  return createPortal(
    <div className="print-report" aria-hidden>
      <header className="pr-head">
        <div>
          <div className="pr-brand">StreamLens</div>
          <div className="pr-muted">Healthy streams, healthy communities.</div>
        </div>
        <div className="pr-right">
          <div className="pr-title">Stream check report</div>
          <div className="pr-muted">Assessment #{a.id} · {date}</div>
          {a.lat != null && a.lon != null && (
            <div className="pr-muted">Location: {a.lat.toFixed(5)}, {a.lon.toFixed(5)}</div>
          )}
        </div>
      </header>

      <section className="pr-risk">
        <div className="pr-score" style={{ color: LEVEL_COLOR[a.risk.level] }}>
          {a.risk.total}
          <span>/100</span>
        </div>
        <div>
          <div className="pr-level" style={{ color: LEVEL_COLOR[a.risk.level] }}>{a.risk.level} One Health risk</div>
          <div>Human {a.risk.human} · Animal {a.risk.animal} · Ecosystem {a.risk.ecosystem}</div>
          <div className="pr-muted">
            Score confidence: {a.risk.score_confidence} · Review status: {a.status.replace(/_/g, " ")}
            {a.mode === "demo" ? " · Demo Mode (rule-based analysis)" : ""}
          </div>
        </div>
      </section>

      <section className="pr-images">
        <figure>
          <img src={a.image_url} alt="" />
          <figcaption>Original photo</figcaption>
        </figure>
        {a.heatmap_url && (
          <figure>
            <img src={a.heatmap_url} alt="" />
            <figcaption>Where the AI looked (heatmap)</figcaption>
          </figure>
        )}
      </section>

      <div className="pr-cols">
        <section>
          <h2>What the AI found</h2>
          {findings.length === 0 ? (
            <p>No visual warning signs found. This does not mean the water is safe.</p>
          ) : (
            <ul>
              {findings.map((f) => (
                <li key={f.id}>{f.display_label}: {Math.round(f.confidence * 100)}% ({f.band})</li>
              ))}
            </ul>
          )}
          <h2>Why this score</h2>
          {contributions.length === 0 ? (
            <p>No risk factors added points.</p>
          ) : (
            <ul>
              {contributions.slice(0, 6).map((c) => (
                <li key={c.key}>
                  {c.label}: +{((c.human + c.animal + c.ecosystem) * 100 / 3).toFixed(1)} points on average
                </li>
              ))}
            </ul>
          )}
        </section>

        <section>
          <h2>Field observations</h2>
          <table>
            <tbody>
              <tr><td>pH</td><td>{val(i.ph)}</td></tr>
              <tr><td>Clarity</td><td>{i.clarity_cm != null ? `${i.clarity_cm} cm` : val(i.clarity_label?.replace("_", " "))}</td></tr>
              <tr><td>Water temperature</td><td>{val(i.temperature_c, " °C")}</td></tr>
              <tr><td>Flow</td><td>{i.flow}</td></tr>
              <tr><td>Smell</td><td>{i.odor}</td></tr>
              <tr><td>Nearby</td><td>{nearby || "None reported"}</td></tr>
            </tbody>
          </table>
          <h2>Data quality checks</h2>
          {a.validation.length === 0 ? (
            <p>Photo and measurements passed all checks.</p>
          ) : (
            <ul>{a.validation.map((v) => <li key={v.code}>{v.message}</li>)}</ul>
          )}
        </section>
      </div>

      <footer className="pr-foot">
        A photo cannot show bacteria, dissolved chemicals or metals. This report is a screening indicator for community
        awareness, not a substitute for laboratory water testing or medical advice. Generated by StreamLens.
      </footer>
    </div>,
    document.body
  );
}
